# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

# https://github.com/calamares/calamares/blob/calamares/src/modules/fstab/fstab.conf
---

crypttabOptions: luks

tmpOptions:
    default:
        tmpfs: false
        options: ""
    ssd:
        tmpfs: true
        options: "defaults,noatime,mode=1777"
